name: print-access-id  # Workflow name

on:
  push:
    branches:
      - masters  # Runs only on the master branch

jobs:
  printaccess:
    runs-on: ubuntu-latest  # Runs on Ubuntu-latest (must be at job level)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checks out repository code

      - name: Print Repository Variable
        env:
          ACCESS_ID: ${{ vars.ACCESS_ID }}  # Fetches the repository variable
        run: echo "The ACCESS_ID is $ACCESS_ID"

